d3d9.enableDialogMode = True
dxvk.hud = fps,version,api
dxvk.hudLeftPos = 0
dxvk.hudTopPos = 0
dxgi.syncInterval = 0
dxgi.maxFrameLatency = 1
d3d9.maxFrameLatency = 1
dxvk.enableGraphicsPipelineLibrary = False
dxgi.tearFree = Auto
d3d9.numBackBuffers = 3
dxvk.enableAsync = true
